language: node_js
node_js:
- '7'
before_install:
- npm install -g firebase-tools

install:
- npm install

before_script:
- npm run build

after_success:
- firebase deploy --token $FIREBASE_TOKEN

branches:
  only:
    - master
    - qa
