language: node_js
node_js:
- '7'
before_install:
- npm install -g firebase-tools

install:
- npm install

before_script:
- npm run build

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "production"
  message: "Production build"
  on:
    branch: master

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
   message: "Staging build"
  on:
    branch: qa

