language: node_js
node_js:
- '7'
before_install:
- npm install -g firebase-tools

cache:
  directories:
    - "node_modules"

install:
- npm install

before_script:
- if [ $TRAVIS_BRANCH == "master" ]; then
    REACT_APP_ENV=production && npm run build
  fi
- if [ $TRAVIS_BRANCH == "qa" ]; then
    REACT_APP_ENV=staging && npm run build
  fi


deploy:
  - provider: script
    skip_cleanup: true
    script: firebase use default && firebase deploy --token $FIREBASE_TOKEN
    on:
      branch: qa
  - provider: script
    skip_cleanup: true
    script: firebase use production && firebase deploy --token $FIREBASE_TOKEN
    on:
      branch: master


