language: node_js
node_js:
- '7'
before_install:
- npm install -g firebase-tools

install:
- npm install


deploy:
  - provider: script
    skip_cleanup: true
    script: REACT_APP_ENV=staging && firebase use default && npm run build && firebase deploy --token $FIREBASE_TOKEN
    on:
      branch: qa
  - provider: script
    skip_cleanup: true
    script: REACT_APP_ENV=production && firebase use production && npm run build && firebase deploy --token $FIREBASE_TOKEN
    on:
      branch: master


