export const LOCALSTOREAGE_STEP_INFO_KEY = 'steps-info';

export const CONFIGURATION_MOVE_LOAD_DATA = 'CONFIGURATION_MOVE_LOAD_DATA';

export const CONFIGURATION_MOVE_RECEIVED_DATA = 'CONFIGURATION_MOVE_RECEIVED_DATA';

export const CONFIGURATION_MOVE_RESET_DATA = 'CONFIGURATION_MOVE_RESET_DATA';
